
package view;


public class ViewTelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public ViewTelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miManterRepublica = new javax.swing.JMenuItem();
        miManterMoradores = new javax.swing.JMenuItem();
        miConfirmarReclamacaoSugestao = new javax.swing.JMenuItem();
        miConvidarMoradoresAceitarConvite = new javax.swing.JMenuItem();
        miCriarRepublica = new javax.swing.JMenuItem();
        miBuscarVagas = new javax.swing.JMenuItem();
        miConsultarResultadoMensal = new javax.swing.JMenuItem();
        miManterReclamacoesSugestoes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miManterPerfil = new javax.swing.JMenuItem();
        miAceitarConvite = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miManterTarefas = new javax.swing.JMenuItem();
        miRegistrarConclusaoDaTarefa = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miManterReceitasEDespesas = new javax.swing.JMenuItem();
        miFazerEstornoDeLancamentos = new javax.swing.JMenuItem();
        miConsultarMinhasReceitasEDespesas = new javax.swing.JMenuItem();
        miRegistrarPagamentoDeReceitaOuDespesas = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("República");

        miManterRepublica.setText("Manter república");
        miManterRepublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManterRepublicaActionPerformed(evt);
            }
        });
        jMenu1.add(miManterRepublica);

        miManterMoradores.setText("Manter moradores");
        miManterMoradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManterMoradoresActionPerformed(evt);
            }
        });
        jMenu1.add(miManterMoradores);

        miConfirmarReclamacaoSugestao.setText("Confirmar solução de reclamações / sugestões");
        miConfirmarReclamacaoSugestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConfirmarReclamacaoSugestaoActionPerformed(evt);
            }
        });
        jMenu1.add(miConfirmarReclamacaoSugestao);

        miConvidarMoradoresAceitarConvite.setText("Convidar moradores/ Aceitar convite");
        miConvidarMoradoresAceitarConvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConvidarMoradoresAceitarConviteActionPerformed(evt);
            }
        });
        jMenu1.add(miConvidarMoradoresAceitarConvite);

        miCriarRepublica.setText("Criar república");
        miCriarRepublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCriarRepublicaActionPerformed(evt);
            }
        });
        jMenu1.add(miCriarRepublica);

        miBuscarVagas.setText("Buscar vagas");
        jMenu1.add(miBuscarVagas);

        miConsultarResultadoMensal.setText("Consultar resultado mensal");
        jMenu1.add(miConsultarResultadoMensal);

        miManterReclamacoesSugestoes.setText("Manter reclamações / sugestões");
        jMenu1.add(miManterReclamacoesSugestoes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Morador");

        miManterPerfil.setText("Manter perfil");
        miManterPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManterPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(miManterPerfil);

        miAceitarConvite.setText("Aceitar convite");
        miAceitarConvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAceitarConviteActionPerformed(evt);
            }
        });
        jMenu2.add(miAceitarConvite);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tarefas");

        miManterTarefas.setText("Manter tarefas");
        miManterTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManterTarefasActionPerformed(evt);
            }
        });
        jMenu3.add(miManterTarefas);

        miRegistrarConclusaoDaTarefa.setText("Registrar conclusão da tarefa");
        miRegistrarConclusaoDaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistrarConclusaoDaTarefaActionPerformed(evt);
            }
        });
        jMenu3.add(miRegistrarConclusaoDaTarefa);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Lançamentos");

        miManterReceitasEDespesas.setText("Manter receitas e despesas");
        miManterReceitasEDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManterReceitasEDespesasActionPerformed(evt);
            }
        });
        jMenu4.add(miManterReceitasEDespesas);

        miFazerEstornoDeLancamentos.setText("Fazer estorno de lançamentos");
        miFazerEstornoDeLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFazerEstornoDeLancamentosActionPerformed(evt);
            }
        });
        jMenu4.add(miFazerEstornoDeLancamentos);

        miConsultarMinhasReceitasEDespesas.setText("Consultar minhas receitas e despesas");
        jMenu4.add(miConsultarMinhasReceitasEDespesas);

        miRegistrarPagamentoDeReceitaOuDespesas.setText("Registrar pagamento de receita ou despesas");
        jMenu4.add(miRegistrarPagamentoDeReceitaOuDespesas);

        jMenuBar1.add(jMenu4);

        miSair.setText("Sair");
        miSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(miSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miFazerEstornoDeLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFazerEstornoDeLancamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miFazerEstornoDeLancamentosActionPerformed

    private void miManterRepublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManterRepublicaActionPerformed

    }//GEN-LAST:event_miManterRepublicaActionPerformed

    private void miManterTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManterTarefasActionPerformed

    }//GEN-LAST:event_miManterTarefasActionPerformed

    private void miCriarRepublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriarRepublicaActionPerformed

    }//GEN-LAST:event_miCriarRepublicaActionPerformed

    private void miManterMoradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManterMoradoresActionPerformed

    }//GEN-LAST:event_miManterMoradoresActionPerformed

    private void miRegistrarConclusaoDaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistrarConclusaoDaTarefaActionPerformed

    }//GEN-LAST:event_miRegistrarConclusaoDaTarefaActionPerformed

    private void miManterReceitasEDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManterReceitasEDespesasActionPerformed

    }//GEN-LAST:event_miManterReceitasEDespesasActionPerformed

    private void miConvidarMoradoresAceitarConviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConvidarMoradoresAceitarConviteActionPerformed

    }//GEN-LAST:event_miConvidarMoradoresAceitarConviteActionPerformed

    private void miConfirmarReclamacaoSugestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConfirmarReclamacaoSugestaoActionPerformed

    }//GEN-LAST:event_miConfirmarReclamacaoSugestaoActionPerformed

    private void miManterPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManterPerfilActionPerformed

    }//GEN-LAST:event_miManterPerfilActionPerformed

    private void miAceitarConviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAceitarConviteActionPerformed
    }//GEN-LAST:event_miAceitarConviteActionPerformed

    private void miSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miSairMouseClicked
        
    }//GEN-LAST:event_miSairMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAceitarConvite;
    private javax.swing.JMenuItem miBuscarVagas;
    private javax.swing.JMenuItem miConfirmarReclamacaoSugestao;
    private javax.swing.JMenuItem miConsultarMinhasReceitasEDespesas;
    private javax.swing.JMenuItem miConsultarResultadoMensal;
    private javax.swing.JMenuItem miConvidarMoradoresAceitarConvite;
    private javax.swing.JMenuItem miCriarRepublica;
    private javax.swing.JMenuItem miFazerEstornoDeLancamentos;
    private javax.swing.JMenuItem miManterMoradores;
    private javax.swing.JMenuItem miManterPerfil;
    private javax.swing.JMenuItem miManterReceitasEDespesas;
    private javax.swing.JMenuItem miManterReclamacoesSugestoes;
    private javax.swing.JMenuItem miManterRepublica;
    private javax.swing.JMenuItem miManterTarefas;
    private javax.swing.JMenuItem miRegistrarConclusaoDaTarefa;
    private javax.swing.JMenuItem miRegistrarPagamentoDeReceitaOuDespesas;
    private javax.swing.JMenu miSair;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenuItem getMiAceitarConvite() {
        return miAceitarConvite;
    }

    public javax.swing.JMenuItem getMiBuscarVagas() {
        return miBuscarVagas;
    }

    public javax.swing.JMenuItem getMiConfirmarReclamacaoSugestao() {
        return miConfirmarReclamacaoSugestao;
    }

    public javax.swing.JMenuItem getMiConsultarMinhasReceitasEDespesas() {
        return miConsultarMinhasReceitasEDespesas;
    }

    public javax.swing.JMenuItem getMiConsultarResultadoMensal() {
        return miConsultarResultadoMensal;
    }

    public javax.swing.JMenuItem getMiConvidarMoradoresAceitarConvite() {
        return miConvidarMoradoresAceitarConvite;
    }

    public javax.swing.JMenuItem getMiCriarRepublica() {
        return miCriarRepublica;
    }

    public javax.swing.JMenuItem getMiFazerEstornoDeLancamentos() {
        return miFazerEstornoDeLancamentos;
    }

    public javax.swing.JMenuItem getMiManterMoradores() {
        return miManterMoradores;
    }

    public javax.swing.JMenuItem getMiManterPerfil() {
        return miManterPerfil;
    }

    public javax.swing.JMenuItem getMiManterReceitasEDespesas() {
        return miManterReceitasEDespesas;
    }

    public javax.swing.JMenuItem getMiManterReclamacoesSugestoes() {
        return miManterReclamacoesSugestoes;
    }

    public javax.swing.JMenuItem getMiManterRepublica() {
        return miManterRepublica;
    }

    public javax.swing.JMenuItem getMiManterTarefas() {
        return miManterTarefas;
    }

    public javax.swing.JMenuItem getMiRegistrarConclusaoDaTarefa() {
        return miRegistrarConclusaoDaTarefa;
    }

    public javax.swing.JMenuItem getMiRegistrarPagamentoDeReceitaOuDespesas() {
        return miRegistrarPagamentoDeReceitaOuDespesas;
    }

    public javax.swing.JMenu getMiSair() {
        return miSair;
    }

    
    
}
